package boardfamily

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// SemanticBoundaryVersion is a pure OFFLINE prototype. No provider, journal,
// CLI flag or accounting profile accepts it. Historical v9 bytes stay v9.
const SemanticBoundaryVersion = "10-semantic-boundaries-offline"

// SourceControl is an application-understood span of the original request.
// It cannot consume a quantity or hide the residual of a compound sentence.
// Defaults apply only to unspecified values. Preserve-requirements is already
// enforced by catalog admission: no substitution or bound weakening is allowed.
type SourceControl struct {
	ClauseID int    `json:"clause_id"`
	Kind     string `json:"kind"`
	Start    int    `json:"start"`
	End      int    `json:"end"`
}

type SemanticBoundaryRequest struct {
	SourceAddressedRequest
	Controls      []SourceControl   `json:"controls"`
	RequiredState map[string]string `json:"required_state"`
	Residuals     []SourceResidual  `json:"residuals"`
}

// Whole-clause grammars intentionally under-recognize. In particular, a keyword
// such as "defaults" never makes an arbitrary requirement disappear. Quoted,
// conditional, negated, extended and compound forms remain model-owned facts.
var boundaryDefaults = regexp.MustCompile(`(?i)^(?:(?:please\s+)?(?:use|keep|apply|retain)\s+(?:the\s+)?(?:normal\s+)?reviewed\s+(?:default\s+)?(?:operating|electrical|supply|power|ambient)(?:\s+and\s+(?:electrical|supply|power|ambient))?\s+(?:limits|defaults)|(?:the\s+)?reviewed\s+(?:default\s+)?(?:operating|electrical|supply|power|ambient)(?:\s+and\s+(?:electrical|supply|power|ambient))?\s+(?:limits|defaults)\s+are\s+(?:fine|acceptable))$`)
var boundaryPreserve = regexp.MustCompile(`(?i)^(?:(?:please\s+)?keep\s+(?:(?:the|that)\s+)?(?:profile\s+and\s+)?all\s+(?:stated|specified|explicit|those)\s+(?:electrical\s+)?(?:values|requirements)\s+unchanged|(?:the\s+)?profile\s+and\s+all\s+(?:stated|specified|explicit)\s+electrical\s+values\s+are\s+to\s+remain\s+unchanged)$`)
var boundaryHeaterOff = regexp.MustCompile(`(?i)^(?:(?:please\s+)?(?:do\s+not|never)\s+(?:run|enable|activate|energize|use)\s+(?:the\s+|its\s+)?heater(?:\s+at\s+any\s+time)?|(?:at\s+startup[,]?\s+)?(?:the\s+|its\s+)?heater\s+(?:must|should)\s+(?:stay|remain|be)\s+off)$`)
var boundaryPullupOnly = regexp.MustCompile(`(?i)^i\s+only\s+mean\s+(?:reducing\s+)?pull[- ]up\s+current,\s+not\s+whole[- ]board\s+(?:power|current)\s+or\s+battery\s+operation$`)
var boundaryUnneededPrefix = regexp.MustCompile(`(?i)^i\s+(?:do\s+not|don't|don’t)\s+need\s+(.+)$`)
var boundaryUnneededSuffix = regexp.MustCompile(`(?i)^(.+)\s+(?:is|are)\s+not\s+(?:needed|required)$`)
var boundarySubject = regexp.MustCompile(`(?i)^(?:pressure(?:\s+measurement)?|humidity(?:\s+measurement)?|temperature(?:\s+measurement)?|wireless(?:\s+telemetry)?|battery\s+operation|heater\s+operation)$`)
var boundaryAnd = regexp.MustCompile(`(?i)\s+and\s+`)
var boundaryScopeAmbiguity = regexp.MustCompile(`(?i)\b(?:if|unless|except|example|examples|quoted?|quoting|hypothetical|previous|previously|rejected|following|preceding|next\s+sentence|above|below|instead|otherwise)\b|\bwhat\s+i\s+(?:do\s+not|don't|don’t)\s+want\b|(?:^|\s)['‘]`)

func boundaryClauseText(text string) string {
	// Remove only sentence framing, never quotes, parentheses, or inner words.
	return strings.TrimSpace(strings.TrimRight(strings.TrimSpace(text), ".!?;"))
}

func boundaryUnneeded(text string) bool {
	match := boundaryUnneededPrefix.FindStringSubmatch(text)
	if match == nil {
		match = boundaryUnneededSuffix.FindStringSubmatch(text)
	}
	if match == nil {
		return false
	}
	for _, subject := range boundaryAnd.Split(match[1], -1) {
		if !boundarySubject.MatchString(subject) {
			return false
		}
	}
	return true
}

// PrepareSemanticBoundaryRequest leaves every original source byte, mention
// identity and quantity role intact. The extra constraints are regenerated by
// both schema construction and decoding; caller mutation cannot change them.
func PrepareSemanticBoundaryRequest(prompt string) (SemanticBoundaryRequest, error) {
	base, err := PrepareSourceAddressedRequest(prompt)
	result := SemanticBoundaryRequest{SourceAddressedRequest: base, Controls: []SourceControl{}, RequiredState: map[string]string{}}
	if err != nil {
		return result, err
	}
	// A local-looking sentence can be a quotation, an exception, or an example
	// governed elsewhere in the request. Conservatively leave such prompts to
	// extraction rather than force a local state across a detected scope cue.
	// This finite guard is not a proof of general English discourse semantics.
	if boundaryScopeAmbiguity.MatchString(prompt) || strings.ContainsAny(prompt, "\"“”()") {
		return withBoundaryResiduals(result), nil
	}
	offset := 0
	for _, clause := range base.Source.Clauses {
		text := boundaryClauseText(clause.Text)
		switch {
		case boundaryDefaults.MatchString(text):
			result.Controls = append(result.Controls, SourceControl{ClauseID: clause.ID, Kind: "reviewed_defaults_for_unspecified_values", Start: offset, End: offset + len(clause.Text)})
		case boundaryPreserve.MatchString(text):
			result.Controls = append(result.Controls, SourceControl{ClauseID: clause.ID, Kind: "preserve_explicit_requirements", Start: offset, End: offset + len(clause.Text)})
		default:
			result.Controls = append(result.Controls, compoundDefaultControls(clause, offset)...)
		}
		for _, mention := range base.Mentions {
			if mention.ClauseID != clause.ID {
				continue
			}
			state := ""
			switch {
			case boundaryUnneeded(text):
				state = "unnecessary_but_allowed"
			case boundaryPullupOnly.MatchString(text) && mention.Kind == "feature" && member(mention.Value, "whole_board_low_power", "battery_operation"):
				state = "unnecessary_but_allowed"
			case boundaryHeaterOff.MatchString(text) && mention.Kind == "feature" && mention.Value == "heater_operation":
				state = "must_not_occur"
			case mention.Kind == "profile" && mention.Value == "standard" && standardOnlyInsideControls(clause, offset, result.Controls):
				state = "context_only"
			}
			if state != "" {
				result.RequiredState[mention.ID] = state
			}
		}
		offset += len(clause.Text)
	}
	return withBoundaryResiduals(result), nil
}

// SemanticBoundarySchema removes model decisions only where the entire source
// clause has a recognized meaning. All other v9 slots and fallbacks remain.
func SemanticBoundarySchema(prompt string) (map[string]any, error) {
	input, err := PrepareSemanticBoundaryRequest(prompt)
	if err != nil {
		return nil, err
	}
	schema, err := SourceAddressedEvidenceSchema(prompt)
	if err != nil {
		return nil, err
	}
	props := schema["properties"].(map[string]any)
	props["version"] = enumSchema(SemanticBoundaryVersion)
	additional := props["additional"].(map[string]any)["properties"].(map[string]any)
	for _, clause := range input.Source.Clauses {
		additional["c"+strconv.Itoa(clause.ID)] = boundaryAdditionalSchema(input, clause.ID)
	}
	mentions := props["mentions"].(map[string]any)["properties"].(map[string]any)
	for id, state := range input.RequiredState {
		mentions[id] = map[string]any{"type": "array", "minItems": 1, "maxItems": 1,
			"items": objectSchema(map[string]any{
				"state": enumSchema(state), "context": map[string]any{"type": "array", "maxItems": 0, "items": map[string]any{"type": "string"}},
			}),
		}
	}
	return schema, nil
}

func semanticBoundaryContext() string {
	return sourceAddressedContext() + `Offline successor rules override v9 only for application-owned controls, residuals and required_state. controls cover exact original UTF-8 byte ranges: reviewed defaults fill only unspecified values; preserve_explicit_requirements forbids substitution or weakened bounds. Control spans are already represented and are not unsupported other facts. residuals retain EVERY byte outside controls, including the rest of a compound sentence. Each additional fact requires a span rN from its own clause. Preserve every substantive residual constraint, including unfamiliar hardware and no-adapter restrictions; use context for other clauses when needed. Only clauses with no residual span must have an empty additional array. Never infer a named profile, numeric value or hardware capability from a defaults control. required_state fixes an unambiguous local mention state; use exactly that one state with empty context. Controls never erase mention or quantity slots and cannot cancel a later heater requirement. This prototype has no provider dispatch.
`
}

// DecodeSemanticBoundaryIntent neither repairs model states nor reinterprets
// historical responses. Violations fail closed with no partial configuration.
// Recognized controls require no additional hardware fact: their semantics are
// already enforced by the unchanged catalog selector and explicit-value checks.
func DecodeSemanticBoundaryIntent(prompt string, raw []byte) (Decision, error) {
	failure := localDecision(prompt, "clarify", "The semantic-boundary extraction could not be validated; no board was generated.", nil)
	if len(raw) > 65536 {
		return failure, errors.New("semantic-boundary evidence exceeds 65536 bytes")
	}
	if err := validateIntentJSON(raw); err != nil {
		return failure, err
	}
	var envelope struct {
		Version    string                       `json:"version"`
		Mentions   map[string][]json.RawMessage `json:"mentions"`
		Additional map[string][]json.RawMessage `json:"additional"`
		Quantities map[string][]json.RawMessage `json:"quantities"`
	}
	if err := json.Unmarshal(raw, &envelope); err != nil {
		return failure, err
	}
	if !exactFields(raw, "version", "mentions", "additional", "quantities") || envelope.Version != SemanticBoundaryVersion {
		return failure, errors.New("invalid semantic-boundary envelope")
	}
	input, err := PrepareSemanticBoundaryRequest(prompt)
	if err != nil {
		return failure, err
	}
	if err := lowerBoundaryAdditional(input, envelope.Additional); err != nil {
		return failure, err
	}
	// Iterate in source order, not map order, for stable first-error diagnostics.
	for _, mention := range input.Mentions {
		state, constrained := input.RequiredState[mention.ID]
		if !constrained {
			continue
		}
		entries := envelope.Mentions[mention.ID]
		if len(entries) != 1 {
			return failure, fmt.Errorf("mention %s requires exactly one source-bound state", mention.ID)
		}
		var entry struct {
			State   string   `json:"state"`
			Context []string `json:"context"`
		}
		if err := json.Unmarshal(entries[0], &entry); err != nil {
			return failure, err
		}
		if entry.State != state || entry.Context == nil || len(entry.Context) != 0 {
			return failure, fmt.Errorf("mention %s in c%d requires %s with local scope", mention.ID, mention.ClauseID, state)
		}
	}
	// An ephemeral internal program, not amended provider output. Old decoders
	// still reject new version bytes, and caller-owned raw remains unchanged.
	envelope.Version = SourceAddressedVersion
	lowered, err := json.Marshal(envelope)
	if err != nil {
		return failure, err
	}
	return DecodeSourceAddressedEvidenceIntent(prompt, lowered)
}
