package boardfamily

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

func TestReferencedProviderSchemaContract(t *testing.T) {
	for _, counts := range [][2]int{{1, 0}, {3, 2}, {32, 128}} {
		schema := referencedIntentSchema(counts[0], counts[1])
		if schema["type"] != "object" || schema["anyOf"] != nil {
			t.Fatal("provider schema needs an object root, not root anyOf")
		}
		var check func(map[string]any)
		check = func(s map[string]any) {
			if union, ok := s["anyOf"].([]any); ok {
				for _, branch := range union {
					check(branch.(map[string]any))
				}
				return
			}
			switch s["type"] {
			case "object":
				if s["additionalProperties"] != false {
					t.Fatal("open provider object")
				}
				props := s["properties"].(map[string]any)
				var keys []string
				for key, child := range props {
					if member(key, "number", "quote", "configuration", "decision") {
						t.Fatalf("model can author prohibited field %s", key)
					}
					keys = append(keys, key)
					check(child.(map[string]any))
				}
				sort.Strings(keys)
				if !reflect.DeepEqual(keys, s["required"]) {
					t.Fatal("not all object fields are required")
				}
			case "array":
				check(s["items"].(map[string]any))
			case "string", "integer":
			default:
				t.Fatalf("unexpected schema type %v", s["type"])
			}
		}
		check(schema)
		root := schema["properties"].(map[string]any)
		branches := root["facts"].(map[string]any)["items"].(map[string]any)["anyOf"].([]any)
		seenNumber := false
		for _, branch := range branches {
			p := branch.(map[string]any)["properties"].(map[string]any)
			kind := p["kind"].(map[string]any)["enum"].([]string)[0]
			seenNumber = seenNumber || kind == "number"
			source := p["sources"].(map[string]any)
			if source["maxItems"] != counts[0] || source["items"].(map[string]any)["maximum"] != counts[0]-1 {
				t.Fatal("source bounds do not match this request")
			}
			q := p["quantities"].(map[string]any)
			if q["items"].(map[string]any)["maximum"] != max(0, counts[1]-1) || q["maxItems"].(int) > counts[1] {
				t.Fatal("quantity bounds do not match this request")
			}
			if counts[1] == 0 && q["maxItems"] != 0 {
				t.Fatal("quantity-free request permits invented quantity IDs")
			}
		}
		if seenNumber != (counts[1] > 0) {
			t.Fatal("numeric branch must exist only when literal quantities exist")
		}
	}
	if !reflect.DeepEqual(ReferencedIntentSchema(), referencedIntentSchema(32, 128)) {
		t.Fatal("exported schema blueprint diverged")
	}
}

// This parses the actual HTTP payload generated by aiprovider.OpenAIProvider.
// It is never sent to a socket: every caller installs an in-memory transport.
func checkReferencedProviderRequest(t testing.TB, r *http.Request, prompt string) int {
	t.Helper()
	if r.Method != "POST" || r.URL.String() != "https://api.openai.com/v1/responses" || r.ContentLength <= 0 || r.ContentLength > 24000 {
		t.Fatal("endpoint/method/byte bounds changed")
	}
	body, err := io.ReadAll(r.Body)
	if closeErr := r.Body.Close(); err != nil || closeErr != nil {
		t.Fatal(errors.Join(err, closeErr))
	}
	if bytes.Contains(body, []byte("offline-referenced-placeholder")) {
		t.Fatal("credential leaked into model input")
	}
	var payload struct {
		Model, Input              string
		MaxOutputTokens           int `json:"max_output_tokens"`
		Background, Store, Stream bool
		Text                      struct {
			Format struct {
				Type, Name string
				Strict     bool
				Schema     map[string]any
			}
		}
	}
	if err := json.Unmarshal(body, &payload); err != nil {
		t.Fatal(err)
	}
	if payload.Model != SelectionModel || payload.MaxOutputTokens != 1600 || payload.Background || payload.Store || !payload.Stream || !payload.Text.Format.Strict || payload.Text.Format.Type != "json_schema" || payload.Text.Format.Name != ReferenceIntentSchemaName {
		t.Fatal("provider model/streaming/schema/token restrictions changed")
	}
	var input struct {
		Prompt            string
		CapabilityContext string `json:"capability_context"`
		Attempt           int
		Diagnostics       []any
	}
	if err := json.Unmarshal([]byte(payload.Input), &input); err != nil {
		t.Fatal(err)
	}
	want, _, err := prepareReferencedGenerateRequest(prompt)
	if err != nil {
		t.Fatal(err)
	}
	if input.Prompt != want.Prompt || input.CapabilityContext != want.CapabilityContext || input.Attempt != 1 || len(input.Diagnostics) != 0 {
		t.Fatal("source/context changed or a recovery attempt was requested")
	}
	a, _ := json.Marshal(payload.Text.Format.Schema)
	b, _ := json.Marshal(want.OutputSchema)
	if !bytes.Equal(a, b) {
		t.Fatal("request-specific provider schema differs from its source contract")
	}
	return len(body)
}

func referencedProviderResponse(t testing.TB, raw []byte, mode, id string) *http.Response {
	return referencedProviderResponseForModel(t, raw, mode, id, SelectionModel)
}

func referencedProviderResponseForModel(t testing.TB, raw []byte, mode, id, model string) *http.Response {
	t.Helper()
	status := "completed"
	var incomplete any
	content := []any{map[string]any{"type": "output_text", "text": string(raw)}}
	inputTokens := 100
	if mode == "incomplete" {
		status, incomplete = "incomplete", map[string]any{"reason": "max_output_tokens"}
	}
	if mode == "wrong-model" {
		model = "not-the-approved-model"
	}
	if mode == "usage-exceeds-reserve" {
		inputTokens = 200000
	}
	if mode == "refusal" {
		content = []any{map[string]any{"type": "refusal", "refusal": "Synthetic provider refusal."}}
	}
	response := map[string]any{"id": id, "model": model, "status": status, "error": nil, "incomplete_details": incomplete,
		"output": []any{map[string]any{"type": "message", "status": "completed", "content": content}},
		"usage":  map[string]any{"input_tokens": inputTokens, "output_tokens": 200, "total_tokens": inputTokens + 200}}
	event := "response." + status
	b, err := json.Marshal(map[string]any{"type": event, "response": response})
	if err != nil {
		t.Fatal(err)
	}
	return &http.Response{StatusCode: 200, Header: http.Header{"Content-Type": []string{"text/event-stream"}},
		Body: io.NopCloser(strings.NewReader("event: " + event + "\ndata: " + string(b) + "\n\n"))}
}

func readReferencedTestLedger(t testing.TB, path string) Ledger {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var l Ledger
	if err := json.Unmarshal(b, &l); err != nil {
		t.Fatal(err)
	}
	return l
}

func TestReferencedProviderKnownPromptsSyntheticResponses(t *testing.T) {
	t.Setenv("OPENAI_API_KEY", "offline-referenced-placeholder")
	t.Setenv("KICADAI_AI_MODEL", "must-not-override-pinned-model")
	minimum, maximum := 24000, 0
	for _, tc := range referencedSyntheticCases() {
		t.Run(tc.id, func(t *testing.T) {
			prompt := retainedTypedSelection(t, tc.id).OriginalRequest
			raw := syntheticReferencedIntent(t, tc.facts...)
			ledger := filepath.Join(t.TempDir(), "ledger.json")
			calls := 0
			transport := roundTripperFunc(func(r *http.Request) (*http.Response, error) {
				calls++
				if calls != 1 {
					t.Fatal("automatic retry")
				}
				size := checkReferencedProviderRequest(t, r, prompt)
				minimum, maximum = min(minimum, size), max(maximum, size)
				return referencedProviderResponse(t, raw, "complete", "offline-"+tc.id), nil
			})
			s, err := interpretReferencedWithTransport(context.Background(), prompt, ledger, LedgerPolicy{"offline-referenced-case", 1, 50000}, transport)
			if err != nil || calls != 1 || s.Outcome != "decision" || s.Decision.Disposition != tc.disposition || !strings.Contains(s.Decision.Message, tc.reason) {
				t.Fatalf("unexpected local synthetic outcome: %+v %v", s, err)
			}
			if !bytes.Equal(s.RawIntent, raw) || len(s.RawDecision) != 0 || s.OriginalRequest != prompt || s.AdmissionVersion != ReferenceIntentVersion || s.ResponseID != "offline-"+tc.id || s.Usage.TotalTokens != 300 {
				t.Fatal("source, raw response, protocol or response identity was lost")
			}
			request, _ := PrepareReferencedRequest(prompt)
			if !reflect.DeepEqual(s.RequestClauses, request.Clauses) || !reflect.DeepEqual(s.SourceQuantities, request.Quantities) {
				t.Fatal("application-owned source table was changed")
			}
			if tc.disposition == "supported" {
				want := Config{"1", tc.family, tc.profile, 3.2, 3.4, 1000, 10, 35, tc.capacitance}
				if s.Decision.Configuration == nil || *s.Decision.Configuration != want {
					t.Fatalf("wrong config: %+v", s.Decision.Configuration)
				}
				checkReferencedGeneratedBundle(t, *s.Decision.Configuration)
			} else if s.Decision.Configuration != nil {
				t.Fatal("non-design outcome exposes a configuration")
			}
			l := readReferencedTestLedger(t, ledger)
			if len(l.Entries) != 1 || l.Entries[0].Status != "completed" || l.Entries[0].ResponseID != s.ResponseID || l.Entries[0].ReserveMicroUSD != 50000 || l.Entries[0].EstimatedMicroUSD != 360 {
				t.Fatal("synthetic accounting is incomplete or allowance was refunded")
			}
		})
	}
	t.Logf("14 known prompts, synthetic responses; actual encoded request sizes %d–%d bytes", minimum, maximum)
}

// The provider output feeds the real deterministic generator, not a simulated
// generator. Compare every file it creates to the existing reviewed example.
// This does not execute the CLI, KiCad validation or manufacturing export; those
// unchanged qualifications are authenticated separately and are not re-scored.
func checkReferencedGeneratedBundle(t *testing.T, c Config) {
	t.Helper()
	for _, key := range []string{"OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY", "GOOGLE_API_KEY"} {
		t.Setenv(key, "")
	}
	family := "bmp280"
	if c.Family == FamilySHT31 {
		family = "sht31"
	}
	published := filepath.Join("..", "..", "examples", "board-family-v2", family+"-"+c.Profile)
	generated := filepath.Join(t.TempDir(), "generated")
	if _, err := Generate(c, generated); err != nil {
		t.Fatal(err)
	}
	compared := 0
	err := filepath.WalkDir(generated, func(path string, entry os.DirEntry, err error) error {
		if err != nil || entry.IsDir() {
			return err
		}
		rel, err := filepath.Rel(generated, path)
		if err != nil {
			return err
		}
		got, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		want, err := os.ReadFile(filepath.Join(published, rel))
		if err != nil {
			return err
		}
		if !bytes.Equal(got, want) {
			return fmt.Errorf("indexed extraction changed reviewed %s/%s", family+"-"+c.Profile, rel)
		}
		compared++
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	t.Logf("synthetic provider → real generator: %s/%s, all %d generated files byte-identical to reviewed example", family, c.Profile, compared)
}

func TestReferencedProviderFailureOutcomesAndAccounting(t *testing.T) {
	for _, mode := range []string{"invalid-extraction", "malformed-json", "transport-failure", "incomplete", "refusal", "wrong-model", "redirect", "rate-limit", "usage-exceeds-reserve", "settlement-lock"} {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("OPENAI_API_KEY", "offline-referenced-placeholder")
			prompt := "Please use BMP280 with fast profile."
			raw := syntheticReferencedIntent(t, referencedChoice("sensor", "BMP280", "required", 0), referencedChoice("profile", "fast", "required", 0))
			if mode == "invalid-extraction" {
				raw = []byte(`{"version":"wrong-version","facts":[]}`)
			} else if mode == "malformed-json" {
				raw = []byte(`{"not":`)
			}
			ledger := filepath.Join(t.TempDir(), "ledger.json")
			calls := 0
			transport := roundTripperFunc(func(r *http.Request) (*http.Response, error) {
				calls++
				checkReferencedProviderRequest(t, r, prompt)
				if calls > 1 {
					t.Fatal("retry or redirect reached transport")
				}
				if mode == "transport-failure" {
					return nil, errors.New("synthetic offline transport failure")
				}
				if mode == "settlement-lock" {
					if err := os.Mkdir(ledger+".lock", 0700); err != nil {
						t.Fatal(err)
					}
				}
				if mode == "redirect" {
					return &http.Response{StatusCode: 307, Header: http.Header{"Location": []string{"https://not-approved.invalid/"}}, Body: io.NopCloser(strings.NewReader(""))}, nil
				}
				if mode == "rate-limit" {
					return &http.Response{StatusCode: 429, Header: http.Header{}, Body: io.NopCloser(strings.NewReader(`{"error":{"message":"synthetic rate limit"}}`))}, nil
				}
				return referencedProviderResponse(t, raw, mode, "offline-failure"), nil
			})
			s, err := interpretReferencedWithTransport(context.Background(), prompt, ledger, LedgerPolicy{"offline-referenced-failure", 1, 50000}, transport)
			if err == nil || calls != 1 || s.Decision.Configuration != nil {
				t.Fatalf("error was ignored or replayed: %+v %v, calls=%d", s, err, calls)
			}
			outcome, ledgerStatus := "provider_failed_or_unknown", "failed_or_unknown"
			switch mode {
			case "invalid-extraction", "malformed-json":
				outcome, ledgerStatus = "invalid_extraction", "completed"
			case "incomplete":
				outcome = "provider_incomplete"
			case "refusal":
				outcome, ledgerStatus = "provider_refusal", "completed"
			case "wrong-model":
				outcome, ledgerStatus = "model_mismatch", "completed"
			case "usage-exceeds-reserve":
				outcome, ledgerStatus = "accounting_failure", "completed"
			case "settlement-lock":
				outcome, ledgerStatus = "accounting_failure", "reserved_unknown_outcome"
			}
			if s.Outcome != outcome {
				t.Fatalf("outcome=%s want=%s", s.Outcome, outcome)
			}
			l := readReferencedTestLedger(t, ledger)
			if len(l.Entries) != 1 || l.Entries[0].Status != ledgerStatus || l.Entries[0].ReserveMicroUSD != 50000 {
				t.Fatalf("incorrect final ledger: %+v", l)
			}
			if member(mode, "invalid-extraction", "wrong-model", "usage-exceeds-reserve", "settlement-lock") && !bytes.Equal(s.RawIntent, raw) {
				t.Fatal("completed structured response lost during later failure")
			}
			if mode == "usage-exceeds-reserve" && l.HaltReason == "" {
				t.Fatal("excessive usage did not halt the ledger")
			}
		})
	}
}

func TestReferencedProviderPreflightAndPayloadBounds(t *testing.T) {
	for _, mode := range []string{"cancelled", "no-key", "no-transport", "invalid-policy", "exhausted", "wrong-budget", "locked", "invalid-prompt", "ordinary-max", "escape-heavy", "quantity-heavy"} {
		t.Run(mode, func(t *testing.T) {
			t.Setenv("OPENAI_API_KEY", "offline-referenced-placeholder")
			prompt := "Please use BMP280."
			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			policy := LedgerPolicy{"offline-referenced-preflight", 1, 50000}
			ledger := filepath.Join(t.TempDir(), "ledger.json")
			switch mode {
			case "cancelled":
				cancel()
			case "no-key":
				t.Setenv("OPENAI_API_KEY", "")
			case "invalid-policy":
				policy.MaxRequests = -1
			case "exhausted", "wrong-budget":
				if _, err := reserveWithPolicy(ledger, policy); err != nil {
					t.Fatal(err)
				}
				if mode == "wrong-budget" {
					policy.MaxRequests = 2
				}
			case "locked":
				if err := os.Mkdir(ledger+".lock", 0700); err != nil {
					t.Fatal(err)
				}
			case "invalid-prompt":
				prompt = " "
			case "ordinary-max":
				prompt = strings.Repeat("x", 2000)
			case "escape-heavy":
				prompt = strings.Repeat(`"`, 2000)
			case "quantity-heavy":
				prompt = strings.Repeat("1 V, ", 128)
			}
			before, _ := os.ReadFile(ledger)
			calls := 0
			var transport http.RoundTripper = roundTripperFunc(func(r *http.Request) (*http.Response, error) {
				calls++
				size := checkReferencedProviderRequest(t, r, prompt)
				t.Logf("%s: actual encoded payload %d bytes", mode, size)
				return nil, errors.New("synthetic offline stop")
			})
			if mode == "no-transport" {
				transport = nil
			}
			s, err := interpretReferencedWithTransport(ctx, prompt, ledger, policy, transport)
			if err == nil || s.Decision.Configuration != nil {
				t.Fatal("preflight/error did not withhold configuration")
			}
			wantCalls := 0
			if mode == "ordinary-max" {
				wantCalls = 1
			}
			if calls != wantCalls {
				t.Fatalf("calls=%d want=%d error=%v", calls, wantCalls, err)
			}
			if calls == 0 {
				if s.Outcome != "no_request" || s.LedgerIndex != 0 {
					t.Fatal("unsent request reported an attempted outcome")
				}
				after, _ := os.ReadFile(ledger)
				if !bytes.Equal(before, after) {
					t.Fatal("rejected request modified existing history")
				}
				if before == nil {
					if _, statErr := os.Stat(ledger); !os.IsNotExist(statErr) {
						t.Fatal("rejected request created a ledger")
					}
				}
			}
			t.Logf("%s: %s (%v)", mode, s.Outcome, err)
		})
	}
}

func ExampleReferencedIntentSchema() {
	schema := ReferencedIntentSchema()
	fmt.Println(schema["type"], schema["additionalProperties"])
	// Output: object false
}
