package promotionrunner

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// These are published historical source identities, not hashes regenerated by CI.
// New versions must handle cleanup errors and must not inherit these exceptions.
var frozenHistoricalLintFiles = map[string]string{
	"specs/ai-requirement-contract-integration/publication-live-v1/replay-audit/main.go": "63cbbf0aa480596d828ef84ef155fb98ff4fdb53913425a0042620b284e40090",
	"specs/practical-board-completion-v1/engine/main.go":                                 "a6f9bcfb270e59aebff2d16aec1013c875e131cb28e08715033fd9080ce46cc8",
}

const frozenHistoricalLintPath = `(^|.*/)(specs/ai-requirement-contract-integration/publication-live-v1/replay-audit/main\.go|specs/practical-board-completion-v1/engine/main\.go)$`

func checkFrozenHistoricalLintFile(path, want string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	if got := fmt.Sprintf("%x", sha256.Sum256(raw)); got != want {
		return fmt.Errorf("frozen lint exception source changed: %s: got %s, want %s; remove the exception and fix the successor, never reseal old evidence", path, got, want)
	}
	return nil
}

func TestFrozenHistoricalLintExceptions(t *testing.T) {
	root := repositoryRootForContractTest(t)
	for path, want := range frozenHistoricalLintFiles {
		if err := checkFrozenHistoricalLintFile(filepath.Join(root, path), want); err != nil {
			t.Error(err)
		}
	}
	config := readContractFile(t, filepath.Join(root, ".golangci.yml"))
	rule := "      - path: " + frozenHistoricalLintPath + "\n        text: '^Error return value of `f\\.Close` is not checked$'\n        linters:\n          - errcheck\n"
	if !strings.Contains(config, rule) {
		t.Fatal("historical exception must retain its exact paths, error and linter")
	}
	workflow := readContractFile(t, filepath.Join(root, ".github/workflows/ci.yml"))
	guard := strings.Index(workflow, "run: go test -count=1 ./internal/promotionrunner -run '^TestFrozenHistoricalLintExceptions'")
	lint := strings.Index(workflow, "- name: Run golangci-lint")
	if guard < 0 || lint < 0 || guard >= lint {
		t.Fatal("CI must verify immutable exception sources before running lint")
	}
}

func TestFrozenHistoricalLintExceptionsRejectChangedOrMissingSource(t *testing.T) {
	path := filepath.Join(t.TempDir(), "main.go")
	const original = "package main\n"
	want := fmt.Sprintf("%x", sha256.Sum256([]byte(original)))
	if err := checkFrozenHistoricalLintFile(path, want); err == nil {
		t.Fatal("missing source accepted")
	}
	for _, text := range []string{original, original + "// changed\n"} {
		if err := os.WriteFile(path, []byte(text), 0o600); err != nil {
			t.Fatal(err)
		}
		err := checkFrozenHistoricalLintFile(path, want)
		if (err == nil) != (text == original) {
			t.Fatalf("source %q: unexpected result: %v", text, err)
		}
	}
}

func TestFrozenHistoricalLintExceptionsDoNotMatchSuccessors(t *testing.T) {
	pattern := regexp.MustCompile(frozenHistoricalLintPath)
	for path := range frozenHistoricalLintFiles {
		if !pattern.MatchString(path) || !pattern.MatchString("/checkout/"+path) {
			t.Errorf("historical path not matched: %s", path)
		}
		for _, successor := range []string{strings.Replace(path, "v1", "v2", 1), strings.Replace(path, "main.go", "other.go", 1), path + ".bak"} {
			if pattern.MatchString(successor) {
				t.Errorf("successor wrongly exempted: %s", successor)
			}
		}
	}
	if pattern.MatchString("internal/boardfamily/main.go") {
		t.Fatal("production code wrongly exempted")
	}
}
